# types of operation

In [ ]:
#add()
#subtract()
#multiply()
#divide()

# Addition()

In [6]:
import numpy as np
a=np.array([[10,20],[30,40]])
a


array([[10, 20],
       [30, 40]])

In [7]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [19]:
print(a)
print(b)

np.add(a,b)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


array([[11, 22],
       [33, 44]])

In [20]:
#diff way to using operator

c=(a+b)
print(c)

[[11 22]
 [33 44]]


# subtract()

In [17]:
print(a)
print(b)

np.subtract(a,b)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


array([[ 9, 18],
       [27, 36]])

In [21]:
c=(a-b)
c

array([[ 9, 18],
       [27, 36]])

# multiply()

In [18]:
print(a)
print(b)

np.multiply(a,b)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


array([[ 10,  40],
       [ 90, 160]])

In [23]:
c=(a*b)
c

array([[ 10,  40],
       [ 90, 160]])

# divide()

In [16]:
print(a)
print(b)
np.divide(a,b)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


array([[10., 10.],
       [10., 10.]])

In [24]:
c=a/b
c

array([[10., 10.],
       [10., 10.]])

# dot() 

In [15]:
#row column multiplication
print(a)
print(b)
np.dot(a,b)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


array([[ 70, 100],
       [150, 220]])