# Numpy

In [16]:
import numpy as np

# creating array using function (array)

In [17]:
a=[[10,20,30],[30,40,50],[15,25,13]]
print(a)
b=np.array(a)
print(b)

[[10, 20, 30], [30, 40, 50], [15, 25, 13]]
[[10 20 30]
 [30 40 50]
 [15 25 13]]


In [18]:
x1=[[10,20],[30,40]]
print(x1)

[[10, 20], [30, 40]]


In [21]:
for row in x1:
    print(row)

[10, 20]
[30, 40]


In [22]:
x2=[[1,2],[3,4]]
x2

[[1, 2], [3, 4]]

In [23]:
for row in x2:
    print(row)

[1, 2]
[3, 4]


In [25]:
x3=x2+x1
x3

[[1, 2], [3, 4], [10, 20], [30, 40]]

In [27]:
for row in x3:
    print (x3)

[[1, 2], [3, 4], [10, 20], [30, 40]]
[[1, 2], [3, 4], [10, 20], [30, 40]]
[[1, 2], [3, 4], [10, 20], [30, 40]]
[[1, 2], [3, 4], [10, 20], [30, 40]]


In [28]:
for row in x3:
    print(row)

[1, 2]
[3, 4]
[10, 20]
[30, 40]


# #creating array into matrix using (np.array)

In [32]:
import numpy as np
a=np.array(x1)
b=np.array(x2)
print(a,type(a))
print(b,type(b))

[[10 20]
 [30 40]] <class 'numpy.ndarray'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


# adding two matrices

In [34]:
c=a+b
print(c)

[[11 22]
 [33 44]]


# multiply the matrix

In [35]:
e=a*b
print(e)

[[ 10  40]
 [ 90 160]]


# dot matrix (row*column multiplication)

In [36]:
f=a.dot(b)
print(f)

[[ 70 100]
 [150 220]]


# list of operation perform on matrix

In [ ]:
#1)array()
#2)arange()
#3)zeroz()
#4)ones()
#5)full()
#6)eye()
#7)identify()
#8)dtype()
#9)ndim()
#10)reshape()
#11)

In [41]:
import numpy as np

l1=[10,20,30,40,50,60,70,80,90]
l2=np.array(l1)
l2
print(l2,type(l2))

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>


# dtype

In [42]:
print(l2.dtype)

int32


# for dimensition use ndim

In [47]:
import numpy as np
l1=[10,20,30,40,50,60,70,80,90]
l2=np.array(l1)
print(l2)
print(l2,type(l2))
print(l2.ndim)    #ndim

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>
1


# converting array into float

In [51]:
a=np.array(l1,dtype=float)
print(a)
print(a.dtype)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]
float64


In [61]:
import numpy as np
x=[1,2,3]
c=np.array(x)

l=[[10,20,30],[40,50,60],[70,80,90]]
y=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l)
print(a)
b=np.array(y)
print(b)
print(c.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1


In [58]:
print(a.ndim)

2


# examale for 3 dimesional

In [66]:
l=[[[10,20,30],[40,50,60],[70,80,90]],[[1,2,3],[4,5,6],[7,8,9]]]
q=np.array(l)
print(q.shape)
print(q.ndim)

(2, 3, 3)
3


# for now shape use obj.shape

In [67]:
l=[[[10,20,30],[40,50,60],[70,80,90]],[[1,2,3],[4,5,6],[7,8,9]]]
q=np.array(l)
print(q.shape)

(2, 3, 3)


# arange function

In [69]:
for x in range(10,16):
    print(x)

10
11
12
13
14
15


# arange():

In [72]:
import numpy as np
a=np.arange(10,90,10)
print(a)
print(a.dtype)


[10 20 30 40 50 60 70 80]
int32


# reshape()

In [75]:
b=a.reshape(4,2)
print(b)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [77]:
x=a.reshape(2,4)
print(x)

[[10 20 30 40]
 [50 60 70 80]]


In [81]:
q=a.reshape(2,2,2)   #(no. of matrix,rows,columns)
print(q)

print(q.ndim)
print(q.shape)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3
(2, 2, 2)


# zeros():

In [83]:
#this contain all elements are zeros

import numpy as np
a=np.zeros(6)
print(a,type(a))

[0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [85]:
b=a.reshape(3,2)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [88]:
z=np.zeros((4,6),dtype=int)
print(z)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [89]:
print(z.shape)

(4, 6)


In [90]:
print(z.ndim)

2


In [96]:
x=z.reshape(6,2,2)
print(x)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


# ones():

In [5]:
#to create matrix of one use ones()

import numpy as np
a=np.ones((4,6),dtype=int)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


# full():

In [6]:
#to create matrix for specific number          syntax:-obj=numpy.full(shape,value,dtype)   

a=np.full(3,9)
print(a,type(a))

[9 9 9] <class 'numpy.ndarray'>


In [7]:
b=np.full((3,4),6)
print(b,type(b))

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]] <class 'numpy.ndarray'>


In [8]:
c=b.reshape(2,3,2)
print(c)

[[[6 6]
  [6 6]
  [6 6]]

 [[6 6]
  [6 6]
  [6 6]]]


# eye():

In [10]:
#creating diagonal matrix (principle matrix)
#syntax   numpy.eye(N,M=none,k=o) k is default
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
b=np.eye(6,dtype=int)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [12]:
b=np.eye(6,k=2,dtype=int)
b

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [13]:
b=np.eye(6,k=-1,dtype=int)
b

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [16]:
x=np.eye(3,4,dtype=int)
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [22]:
import numpy as np

p=np.eye(4,3,k=-1,dtype=int)
p

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# identity():

In [24]:
#it is use to create identity matrix  ex:- 2x2,3x3,4x4
#syntax:-  obj=numpy.identity(value,dtype)
import numpy as np
a=np.identity(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
a=np.identity(5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])