# boolean array

In [5]:
#step1:-prepared boolean aaray, ehich contains tre and false values
#syntax: obj=ndarray with condition
#step2:- pass the boolean aaray obj to ndarray object
#syntax:-obj=ndarray[booleanarray]



#obtain negative numbers

import numpy as np
p=np.array([10,-5,12,-4,-10,1,4])
print(p)
a=p<0
print(a)
print(p[a])

[ 10  -5  12  -4 -10   1   4]
[False  True False  True  True False False]
[ -5  -4 -10]


In [6]:
#approach number 2
#shortcut
import numpy as np
p=np.array([10,-5,12,-4,-10,1,4])
z=p[p<0]
print(z)

[ -5  -4 -10]


In [7]:
#step1:-prepared boolean aaray, ehich contains tre and false values
#syntax: obj=ndarray with condition
#step2:- pass the boolean aaray obj to ndarray object
#syntax:-obj=ndarray[booleanarray]



#obtain positive numbers

import numpy as np
p=np.array([10,-5,12,-4,-10,1,4])
print(p)
a=p>0
print(a)
print(p[a])

[ 10  -5  12  -4 -10   1   4]
[ True False  True False False  True  True]
[10 12  1  4]


In [8]:
#approach number 2
#shortcut
import numpy as np
p=np.array([10,-5,12,-4,-10,1,4])
z=p[p>0]
print(z)

[10 12  1  4]


In [12]:
#obtain odd and even nmbers from ndarray ob

import numpy as np
a=np.array([1,2,3,17,5,6,21,22,19])
print(a)
od=a[a%2!=0]
eve=a[a%2==0]
print("odd numbers are:",od)
print("even nmbers are:",eve)


[ 1  2  3 17  5  6 21 22 19]
odd numbers are: [ 1  3 17  5 21 19]
even nmbers are: [ 2  6 22]
