# types of statistical operation

In [ ]:
#amax()
#amin()
#mean()
#median()
#varience() or var()
#standard deviation or std()

# 1)amax

In [4]:
#use for finding max values from array
#syntax:-  obj=numpy.amax(ndarray)


import numpy as np

a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
maxv=np.amax(a)
print(maxv)

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]
60


In [7]:
#column vise maximum value i want to find  note:-(0=column),(1=row)
colmax=np.amax(a,axis=0)
print(colmax)


[40 50 60]


# 2)amin():

In [8]:
#use for finding min values from array
#syntax:-  obj=numpy.amin(ndarray)


import numpy as np

a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
minv=np.amin(a)
print(minv)

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]
1


In [9]:
#row vise minimum value i want to find  note:-(0=column),(1=row)
rmin=np.amin(a,axis=1)
print(rmin)


[10 40  1]


# 3)mean():

In [ ]:
#sum of all elements of array divided by total number of elements in aaray
#syntax:-  obj=numpy.mean(ndarray)
#syntax:-  obj=numpy.mean(ndarray,axis=0)---------->for columns
#syntax:-  obj=numpy.mean(ndarray,axis=1)---------->for rows

In [12]:
import numpy as np

a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
res=np.mean(a)
print(res)

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]
29.666666666666668


In [13]:
#for calculate mean value of columns
c=np.mean(a,axis=0)
print(c)

[17. 27. 45.]


In [15]:
#for calculate mean value of row
r=np.mean(a,axis=1)
print(r)

[20. 50. 19.]


# 4)median():

In [18]:
#first matrx arrange values in accending value ex:-(1, 10, 11, 20,30,40,45,50,60) median=30
#center value finds

import numpy as np


a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
md=np.median(a)
print(md)

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]
30.0


In [26]:
#to find medium column wise
import numpy as np
a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
colmed=np.median(a,axis=0)
print()

print(colmed)


[[10 20 30]
 [40 50 60]
 [ 1 11 45]]

[10. 20. 45.] 

In [27]:
#to find medium row wise
import numpy as np
a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
rowmed=np.median(a,axis=1)
print()

print(rowmed)

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]

[20. 50. 11.]


# 4)var():

In [ ]:
#
#formula:-  variance=square(xi-mean)/total numbers of elements


#syntax:-   obj=numpy.var(ndarrayobj)
#syntax:-  obj=numpy.var(ndarray,axis=0)----> var for column wise
#syntax:-  obj=numpy.var(ndarray,axis=1)----> var for row wise

In [36]:
import numpy as np

a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
m=np.mean(a)

print()
print("mean:",m)
s=np.var(a)

print("var:",s)  #how it is work  (10-29)^2+(20-29)^2+(30-29)^2+(40-29)^2....../9=29.666

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]

mean: 29.666666666666668
var: 369.55555555555554


In [41]:
#var for column wise
x=np.mean(a)
print(x)
var=np.var(a)
print(var)
varc=np.var(a,axis=0)
print(varc)

29.666666666666668
369.55555555555554
[278. 278. 150.]


In [42]:
#var for row wise
x=np.mean(a)
print(x)
var=np.var(a)
print(var)
varr=np.var(a,axis=1)
print(varr)

29.666666666666668
369.55555555555554
[ 66.66666667  66.66666667 354.66666667]


# 5)std():

In [ ]:
#std means square root of var

#formula for standard deviation --> std=sqrt(var)


#syntax:-   obj=numpy.std(ndarrayobj)
#syntax:-  obj=numpy.std(ndarray,axis=0)----> std for column wise
#syntax:-  obj=numpy.std(ndarray,axis=1)----> std for row wise

In [47]:
import numpy as np

a=np.array([[10,20,30],[40,50,60],[1,11,45]])
print(a)
var=np.var(a)
print("var",var)
sd=np.std(a)
print("std",sd)

[[10 20 30]
 [40 50 60]
 [ 1 11 45]]
var 369.55555555555554
std 19.223827807061618
